### ISSUE TITLE
search bar is not working for name 

### ISSUE THREAD

**Issue by saeedafatima** [O16Labs-Khi/HungerAdvisor#100]
open search bar 
write beef
only dishes with the work dish should show
enter search 

steps :

write burger in search bar why it is not showing in search bar. ?

**Comment by saeedafatima** [comment]
write burger in search bar why it is not showing in search bar. ?

**Comment by Hamdansh615** [comment]
default rating 1 was going in api hit from app side that is why data was not showing correctly fixed it now default value is 0 retest again in new build
