### ISSUE TITLE
no toast msg is showing when invalid code is entered.

### ISSUE THREAD

**Issue by saeedafatima** [O16Labs-Khi/HungerAdvisor#108]
edit profile
enter valid number
sms will going to be received
now enter wrong code
blank toast is showing

not fixed -now no toast msg is showing

**Comment by saeedafatima** [comment]
not fixed

**Comment by saeedafatima** [comment]
bug dependency > this will resolved when a invalid toast msg will get resolved

**Comment by saeedafatima** [comment]
cant retest - this will resolved when a invalid toast msg will get resolved

**Comment by saeedafatima** [comment]
Cant retest . Because on entering valid number --->invalid number toast message is showing. Some twillio work . Assigning to danish

**Comment by danishO16** [comment]
Fixed you may check it now. @saeedafatima
