### ISSUE TITLE
warning error toast message kept on coming till 5 secs even tapped back> no steps to reproduce 

### ISSUE THREAD

**Issue by saeedafatima** [O16Labs-Khi/HungerAdvisor#153]
![image](https://user-images.githubusercontent.com/78846278/110075673-fb59b180-7da4-11eb-9cc7-1f123da63cce.png)

this is the case i have experiend few times > rare but almost failed to take a screenshot cox it just disappears after 5 secs
no stp cox i was doing noting phone was on table and suddenly saw these errors on phone so took the ss

**Comment by Hamdansh615** [comment]
com.facebook.katana ye hamre app ka bundle identifier hi nai kisi aur app ka hai not a bug

**Comment by Hamdansh615** [comment]
![image](https://user-images.githubusercontent.com/40858451/113717201-d094ad00-9704-11eb-88be-3609bcd6893c.png)
