### ISSUE TITLE
on search -->when ambiance + kitchen is specified--irrelevant dishes are showing 

### ISSUE THREAD

**Issue by saeedafatima** [O16Labs-Khi/HungerAdvisor#156]
on search -->when ambiance + kitchen is specified--irrelevant dishes are showing 

burger lab clifton branch have dishes cheese loader dish and this branch have pakistani kitchen and following Ambience
Another Ambience
Games and entertainment activities for children
Games and entertainment activities for adults
Outdoor seating
free delivery
Molasses

if i select beachfront ambience and brazalian kitchen then cheese loader should not show

**Comment by Hamdansh615** [comment]
backend issue
