### ISSUE TITLE
slider on coupons is not working 

### ISSUE THREAD

**Issue by saeedafatima** [O16Labs-Khi/HungerAdvisor#159]
step to reproduce

1)open app
2) scroll down to coupon
3) slider is not working on coupons.

**Comment by Hamdansh615** [comment]
only 1 dish is added look at the red dot in every coupon when they 2 or 3 then you can swipe not a bug only 1 dish is added in that coupon

**Comment by saeedafatima** [comment]
not fixed > I will show you myself
