### ISSUE TITLE
Turn off Available option, showing all Search Results. 

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#171]
When we turn off 'Available' option from the Super Admin Panel, nothing display on Home Screen but when we try to search and tap to Search button, its displaying all search results. 

- Go -> Home Screen
- Tap to Search 
- Hit Search Button

**Comment by Mustafa016** [comment]
GR will fix this issue

**Comment by o16-ghulam-rasool** [comment]
fixed

**Comment by Mustafa016** [comment]
fixed & closed
