### ISSUE TITLE
In Edit Blog Page, Add Validation message to highlight input.

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#172]
![blog-error](https://user-images.githubusercontent.com/83067788/116056230-fb847800-a696-11eb-90b8-115f57e926b2.png)

Go Super Admin Panel -> Blogs -> Edit Blog
- Select Restaurant with empty select dish ->tap to Submit -> Replace There is some error red alert message to Validation Message 'this field is required'.

**Comment by hamidkhan-o16** [comment]
Done
