### ISSUE TITLE
Resolve this issue 'sidebar.select_ambience' in Edit FSP section.

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#174]
![select-amb-issue](https://user-images.githubusercontent.com/83067788/116059210-0b518b80-a69a-11eb-8ea2-1fd3679addd3.png)

- In Super Admin Panel -> Go Food Service Provider -> Tap Edit Icon -> Replace 'sidebar.select_ambience' to 'Select Ambience' .

**Comment by hamidkhan-o16** [comment]
![image](https://user-images.githubusercontent.com/78070354/119347901-96cc3580-bcb5-11eb-9817-9b81d42b9335.png)

Done
