### ISSUE TITLE
Web Admin Panel Issue, In Add Blog -> Preferable image size: 500x-500x issue.

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#177]
![image-size-issue](https://user-images.githubusercontent.com/83067788/116066775-d5b0a080-a6a1-11eb-91b7-7d624c366d69.png)

**When we tap to Add Blog or Edit Blog, and try to upload image with 150x150 it's uploading, kindly set the validation according to this size 500x-500x.** 

- GO Super Admin -> Blogs -> Add Blog -> Upload Image with any size it's uploading.

**Comment by hamidkhan-o16** [comment]
Its clearly mention over their that PREFERABLE SIZE of image is 500 x 500
it does not mean that only a image having dimension 500 x 500 is eligible.

**Comment by saeedafatima** [comment]
@Mustafa016 please check if image greater than 500*500 is uploaded then how its displayed
