### ISSUE TITLE
Email Formatting Issues... All kind of Forms Submission (Login, Register ,Occasion Designer, List Your Business, Think With Us)

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#184]
These kind of emails are un-acceptable.

![116963583-ae218f80-acc2-11eb-9de9-96eb0a78bf2d](https://user-images.githubusercontent.com/83067788/119497126-a1ea9880-bd7d-11eb-9dc7-89f03cbbde3d.png)

**Comment by hamidkhan-o16** [comment]
Done

**Comment by saeedafatima** [comment]
fixed & closed

**Comment by Mustafa016** [comment]
FIXED & Closed
