### ISSUE TITLE
IOS & Android -- UI Issue - Menu Profile, Edit Profile, Blogs .. see attach. screenshots

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#194]
SS 1:

![h-ui](https://user-images.githubusercontent.com/83067788/119696163-55c85280-be68-11eb-9636-79048b6d5bd0.JPEG)

SS 2:

![h-ui-blog](https://user-images.githubusercontent.com/83067788/119696168-56f97f80-be68-11eb-8031-c35be1afa645.jpeg)

SS 3:

![h-uiissue](https://user-images.githubusercontent.com/83067788/119696173-582aac80-be68-11eb-8753-ed304cfea5e2.png)

**Comment by Hamdansh615** [comment]
fixed

**Comment by Mustafa016** [comment]
fixed in IOS -- but not in Android
