### ISSUE TITLE
API Issue -- Recommended Search filter also showing other countries results, see attach. video

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#197]
https://user-images.githubusercontent.com/83067788/119839305-828a7180-bf1d-11eb-880a-5015ced5f195.mp4

**Comment by GhulamRasoolNunari** [comment]
Fixed, but i can't assign any one. maybe i don't have any permission

**Comment by Mustafa016** [comment]
fixed & closed
