### ISSUE TITLE
Edit Blogs data showing blanks -- Previous blogs data missing, title missing

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#198]
https://user-images.githubusercontent.com/83067788/119845516-c59b1380-bf22-11eb-8040-d5b43d4a5a97.mp4

**Comment by GhulamRasoolNunari** [comment]
Fixed, but i can't assign any one. maybe i don't have any permission

**Comment by Mustafa016** [comment]
fixed and closed
