### ISSUE TITLE
In Recommendation filter, Add Pagination to find all results if required ( its showing only 10 Results on screen) 

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#199]
I added the new dish with the following Details : 
City: Makkah 
For More Detail.. attach. Screenshot

![image_2021_05_31T13_13_33_882Z](https://user-images.githubusercontent.com/83067788/120205107-048ed900-c243-11eb-8ca7-17383cb0bd94.png)

Video:

https://user-images.githubusercontent.com/83067788/120204052-d066e880-c241-11eb-94d7-c82c5795044e.mp4

**Comment by o16-ghulam-rasool** [comment]
done
pagination not added. but listing all recommended dishes

**Comment by Mustafa016** [comment]
fixed & closed
